// Intel Proprietary
// 
// Copyright 2021 Intel Corporation All Rights Reserved.
// 
// Your use of this software is governed by the TDX Source Code LIMITED USE LICENSE.
// 
// The Materials are provided "as is," without any express or implied warranty of any kind including warranties
// of merchantability, non-infringement, title, or fitness for a particular purpose.

/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  Spreadsheet Format Version - '6'
 **/

#include "auto_gen/cpuid_configurations.h"

// Lookup table first MAX_NUM_CPUID_CONFIG entries will be in the same order as in cpuid_configurable table

const cpuid_lookup_t cpuid_lookup[MAX_NUM_CPUID_LOOKUP] = {
  { // ENTRY_NUM = 0 
  .leaf_subleaf = {.leaf = 0x1, .subleaf = 0xffffffff},
  .verify_mask = { .ebx = 0xff00, .ecx = 0x47faa217, .edx = 0x1fa9fbff },
  .verify_value = { .ebx = 0x800, .ecx = 0x47faa217, .edx = 0x1fa9fbff },
  .verify_same = { .eax = 0xf000c000, .ebx = 0xffff, .ecx = 0xf7ffff9f, .edx = 0xffffffff },
  .fixed1 = { .ecx = 0x80000000, .edx = 0x200 },
  .fixed0_or_dynamic = { .eax = 0xf000c000, .ebx = 0xff0000ff, .ecx = 0x8010060, .edx = 0x40120400 }
  },
  { // ENTRY_NUM = 1 
  .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x0},
  .verify_mask = { .ebx = 0xfff },
  .verify_value = { .ebx = 0x3f },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0x3c00, .edx = 0x4 }
  },
  { // ENTRY_NUM = 2 
  .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x1},
  .verify_mask = { .ebx = 0xfff },
  .verify_value = { .ebx = 0x3f },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0x3c00, .edx = 0x4 }
  },
  { // ENTRY_NUM = 3 
  .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x2},
  .verify_mask = { .ebx = 0xfff },
  .verify_value = { .ebx = 0x3f },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0x3c00, .edx = 0x4 }
  },
  { // ENTRY_NUM = 4 
  .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x3},
  .verify_mask = { .eax = 0xe0, .ebx = 0xfff, .edx = 0x1 },
  .verify_value = { .eax = 0x60, .ebx = 0x3f, .edx = 0x0 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0x3c00, .edx = 0xfffffff8 }
  },
  { // ENTRY_NUM = 5 
  .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x0},
  .verify_mask = { .eax = 0xffffffff, .ebx = 0x219424c3, .ecx = 0x99000000, .edx = 0xfc082600 },
  .verify_value = { .eax = 0x2, .ebx = 0x219424c3, .ecx = 0x99000000, .edx = 0xfc080400 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xfffffffb, .ecx = 0xbfc1ff6f, .edx = 0xffebffff },
  .fixed0_or_dynamic = { .ebx = 0x404006, .ecx = 0x643e8010, .edx = 0x2218c3 }
  },
  { // ENTRY_NUM = 6 
  .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x1},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xfbffe28f, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 7 
  .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x2},
  .verify_mask = { .edx = 0x17 },
  .verify_value = { .edx = 0x17 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffc0 }
  },
  { // ENTRY_NUM = 8 
  .leaf_subleaf = {.leaf = 0xa, .subleaf = 0xffffffff},
  .verify_mask = { .eax = 0xff00, .ecx = 0xffffff80, .edx = 0x8000 },
  .verify_value = { .eax = 0x800, .ecx = 0x0, .edx = 0x8000 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffff6000 }
  },
  { // ENTRY_NUM = 9 
  .leaf_subleaf = {.leaf = 0x1c, .subleaf = 0xffffffff},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 10 
  .leaf_subleaf = {.leaf = 0x23, .subleaf = 0x0},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xffffffc0, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 11 
  .leaf_subleaf = {.leaf = 0x80000008, .subleaf = 0xffffffff},
  .verify_mask = { .eax = 0xff, .ebx = 0x200 },
  .verify_value = { .eax = 0x34, .ebx = 0x200 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xffff0000, .ebx = 0xfffffdff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 12 
  .leaf_subleaf = {.leaf = 0x0, .subleaf = 0xffffffff},
  .verify_mask = { .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .verify_value = { .ebx = 0x756e6547, .ecx = 0x6c65746e, .edx = 0x49656e69 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed1 = { .eax = 0x23 },
  .fixed0_or_dynamic = { .eax = 0xffffffdc }
  },
  { // ENTRY_NUM = 13 
  .leaf_subleaf = {.leaf = 0x3, .subleaf = 0xffffffff},
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 14 
  .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x4},
  .verify_mask = { .eax = 0x1f },
  .verify_value = { .eax = 0x0 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 15 
  .leaf_subleaf = {.leaf = 0x6, .subleaf = 0xffffffff},
  .faulting = true,
  .verify_mask = { .eax = 0x800000 },
  .verify_value = { .eax = 0x0 },
  .verify_same = { .eax = 0x800000 }
  },
  { // ENTRY_NUM = 16 
  .leaf_subleaf = {.leaf = 0x8, .subleaf = 0xffffffff},
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 17 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x0},
  .verify_mask = { .eax = 0x3 },
  .verify_value = { .eax = 0x3 },
  .verify_same = { .eax = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xfff9fd18, .ebx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 18 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x1},
  .verify_mask = { .eax = 0xf, .ecx = 0x1800 },
  .verify_value = { .eax = 0xf, .ecx = 0x1800 },
  .verify_same = { .eax = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xffffffe0, .ebx = 0xffffffff, .ecx = 0xffff26ff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 19 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x2},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 20 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x3},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 21 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x4},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 22 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x5},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 23 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x6},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 24 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x7},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 25 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x8},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 26 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x9},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 27 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xa},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 28 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xb},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 29 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xc},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 30 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xd},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 31 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xe},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 32 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xf},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 33 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x10},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 34 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x11},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 35 
  .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x12},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 36 
  .leaf_subleaf = {.leaf = 0xe, .subleaf = 0xffffffff},
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 37 
  .leaf_subleaf = {.leaf = 0x11, .subleaf = 0xffffffff},
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 38 
  .leaf_subleaf = {.leaf = 0x12, .subleaf = 0xffffffff},
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 39 
  .leaf_subleaf = {.leaf = 0x13, .subleaf = 0xffffffff},
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 40 
  .leaf_subleaf = {.leaf = 0x14, .subleaf = 0x0},
  .verify_mask = { .eax = 0xffffffff },
  .verify_value = { .eax = 0x1 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 41 
  .leaf_subleaf = {.leaf = 0x14, .subleaf = 0x1},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 42 
  .leaf_subleaf = {.leaf = 0x15, .subleaf = 0xffffffff},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed1 = { .eax = 0x1, .ecx = 0x17d7840 },
  .fixed0_or_dynamic = { .eax = 0xfffffffe, .ecx = 0xfe8287bf, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 43 
  .leaf_subleaf = {.leaf = 0x19, .subleaf = 0xffffffff},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xfffffffe, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xfffffff8, .ebx = 0xffffffeb, .ecx = 0xfffffffd, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 44 
  .leaf_subleaf = {.leaf = 0x1d, .subleaf = 0x0},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 45 
  .leaf_subleaf = {.leaf = 0x1d, .subleaf = 0x1},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 46 
  .leaf_subleaf = {.leaf = 0x1e, .subleaf = 0xffffffff},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 47 
  .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x0},
  .faulting = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff }
  },
  { // ENTRY_NUM = 48 
  .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x1},
  .faulting = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff }
  },
  { // ENTRY_NUM = 49 
  .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x2},
  .faulting = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff }
  },
  { // ENTRY_NUM = 50 
  .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x3},
  .faulting = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff }
  },
  { // ENTRY_NUM = 51 
  .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x4},
  .faulting = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff }
  },
  { // ENTRY_NUM = 52 
  .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x5},
  .faulting = true,
  .verify_mask = { .ecx = 0xff00 },
  .verify_value = { .ecx = 0x0 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff }
  },
  { // ENTRY_NUM = 53 
  .leaf_subleaf = {.leaf = 0x20, .subleaf = 0xffffffff},
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 54 
  .leaf_subleaf = {.leaf = 0x21, .subleaf = 0x0},
  .fixed1 = { .eax = 0x0, .ebx = 0x65746e49, .ecx = 0x20202020, .edx = 0x5844546c },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0x9a8b91b6, .ecx = 0xdfdfdfdf, .edx = 0xa7bbab93 }
  },
  { // ENTRY_NUM = 55 
  .leaf_subleaf = {.leaf = 0x22, .subleaf = 0xffffffff},
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 56 
  .leaf_subleaf = {.leaf = 0x23, .subleaf = 0x1},
  .verify_mask = { .eax = 0xffffff00 },
  .verify_value = { .eax = 0x0 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 57 
  .leaf_subleaf = {.leaf = 0x23, .subleaf = 0x2},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 58 
  .leaf_subleaf = {.leaf = 0x23, .subleaf = 0x3},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 59 
  .leaf_subleaf = {.leaf = 0x80000000, .subleaf = 0xffffffff},
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed1 = { .eax = 0x80000008 },
  .fixed0_or_dynamic = { .eax = 0x7ffffff7, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff }
  },
  { // ENTRY_NUM = 60 
  .leaf_subleaf = {.leaf = 0x80000001, .subleaf = 0xffffffff},
  .verify_mask = { .ecx = 0x121, .edx = 0x2c100800 },
  .verify_value = { .ecx = 0x121, .edx = 0x2c100800 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xfffffede, .edx = 0xd3efffff }
  },
  { // ENTRY_NUM = 61 
  .leaf_subleaf = {.leaf = 0x80000006, .subleaf = 0xffffffff},
  .faulting = true,
  .verify_mask = { .ecx = 0xff },
  .verify_value = { .ecx = 0x40 },
  .verify_same = { .ecx = 0xff }
  },
  { // ENTRY_NUM = 62 
  .leaf_subleaf = {.leaf = 0x80000007, .subleaf = 0xffffffff},
  .verify_mask = { .edx = 0x100 },
  .verify_value = { .edx = 0x100 },
  .verify_same = { .edx = 0x100 },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xfffffeff }
  }
};

const cpuid_configurable_t cpuid_configurable[MAX_NUM_CPUID_CONFIG] = {
  { // ENTRY_NUM = 0 
  .leaf_subleaf = {.leaf = 0x1, .subleaf = 0xffffffff},
  .config_direct = { .ebx = 0xff0000 },
  .allow_direct = { .ecx = 0x31044d88, .edx = 0xb8440000 }
  },
  { // ENTRY_NUM = 1 
  .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x0},
  .config_direct = { .eax = 0xffffc3ff, .ebx = 0xfffff000, .ecx = 0xffffffff, .edx = 0xfffffffb }
  },
  { // ENTRY_NUM = 2 
  .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x1},
  .config_direct = { .eax = 0xffffc3ff, .ebx = 0xfffff000, .ecx = 0xffffffff, .edx = 0xfffffffb }
  },
  { // ENTRY_NUM = 3 
  .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x2},
  .config_direct = { .eax = 0xffffc3ff, .ebx = 0xfffff000, .ecx = 0xffffffff, .edx = 0xfffffffb }
  },
  { // ENTRY_NUM = 4 
  .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x3},
  .config_direct = { .eax = 0xffffc3ff, .ebx = 0xfffff000, .ecx = 0xffffffff, .edx = 0x7 }
  },
  { // ENTRY_NUM = 5 
  .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x0},
  .allow_direct = { .ebx = 0xdc2b9b18, .ecx = 0x2417f65, .edx = 0x5c11c }
  },
  { // ENTRY_NUM = 6 
  .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x1},
  .allow_direct = { .eax = 0x4001d70 }
  },
  { // ENTRY_NUM = 7 
  .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x2},
  .allow_direct = { .edx = 0x28 }
  },
  { // ENTRY_NUM = 8 
  .leaf_subleaf = {.leaf = 0xa, .subleaf = 0xffffffff}
  },
  { // ENTRY_NUM = 9 
  .leaf_subleaf = {.leaf = 0x1c, .subleaf = 0xffffffff},
  .allow_direct = { .eax = 0xff }
  },
  { // ENTRY_NUM = 10 
  .leaf_subleaf = {.leaf = 0x23, .subleaf = 0x0},
  .allow_direct = { .eax = 0xf }
  },
  { // ENTRY_NUM = 11 
  .leaf_subleaf = {.leaf = 0x80000008, .subleaf = 0xffffffff},
  .allow_direct = { .ebx = 0x200 }
  }
};

const cpuid_config_return_values_t xfam_mask_0x1_0xffffffff[XCR0_MAX_VALID_BIT + 1] = {

    [2]={ .ecx = 0x30001000  } ,

};

const cpuid_config_return_values_t xfam_mask_0x7_0x0[XCR0_MAX_VALID_BIT + 1] = {

    [2]={ .ebx = 0x20 , .ecx = 0x600  } ,
    [5]={ .ebx = 0xdc230000 , .ecx = 0x5842 , .edx = 0x80010c  } ,
    [6]={ .ebx = 0xdc230000 , .ecx = 0x5842 , .edx = 0x80010c  } ,
    [7]={ .ebx = 0xdc230000 , .ecx = 0x5842 , .edx = 0x80010c  } ,
    [8]={ .ebx = 0x2000000  } ,
    [9]={ .ecx = 0x8  } ,
    [11]={ .ecx = 0x80 , .edx = 0x100000  } ,
    [12]={ .ecx = 0x80 , .edx = 0x100000  } ,
    [14]={ .edx = 0x20  } ,
    [15]={ .edx = 0x80000  } ,
    [17]={ .edx = 0x3400000  } ,
    [18]={ .edx = 0x3400000  } ,

};

const cpuid_config_return_values_t xfam_mask_0x7_0x1[XCR0_MAX_VALID_BIT + 1] = {

    [5]={ .eax = 0x30  } ,
    [6]={ .eax = 0x30  } ,
    [7]={ .eax = 0x30  } ,

};

const cpuid_config_return_values_t xfam_mask_0xd_0x0[XCR0_MAX_VALID_BIT + 1] = {

    [2]={ .eax = 0x4  } ,
    [5]={ .eax = 0xe0  } ,
    [6]={ .eax = 0xe0  } ,
    [7]={ .eax = 0xe0  } ,
    [9]={ .eax = 0x200  } ,
    [17]={ .eax = 0x60000  } ,
    [18]={ .eax = 0x60000  } ,

};

const cpuid_config_return_values_t xfam_mask_0xd_0x1[XCR0_MAX_VALID_BIT + 1] = {

    [8]={ .ecx = 0x100  } ,
    [11]={ .ecx = 0x1800  } ,
    [12]={ .ecx = 0x1800  } ,
    [14]={ .ecx = 0x4000  } ,
    [15]={ .ecx = 0x8000  } ,

};


