// Intel Proprietary
// 
// Copyright 2021 Intel Corporation All Rights Reserved.
// 
// Your use of this software is governed by the TDX Source Code LIMITED USE LICENSE.
// 
// The Materials are provided "as is," without any express or implied warranty of any kind including warranties
// of merchantability, non-infringement, title, or fitness for a particular purpose.

/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  Spreadsheet Format Version - '2'
 **/

#include "auto_gen/global_sys_fields_lookup.h"


const md_lookup_t global_sys_lookup[MAX_NUM_GLOBAL_SYS_LOOKUP] = {
 {
   // NUM_PKGS // 0
   .field_id =  { .raw  = 0x0000000200000000 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // PKG_FMS // 1
   .field_id =  { .raw  = 0x0000000200000001 },
   .num_of_fields = 8, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_MB, .mig_import = MIG_CBO 
 },
 {
   // VENDOR_ID // 2
   .field_id =  { .raw  = 0x0800000200000000 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_MB, .mig_import = MIG_CBO 
 },
 {
   // BUILD_DATE // 3
   .field_id =  { .raw  = 0x8800000200000001 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_MB, .mig_import = MIG_CBO 
 },
 {
   // BUILD_NUM // 4
   .field_id =  { .raw  = 0x8800000100000002 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (-1ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_MB, .mig_import = MIG_CBO 
 },
 {
   // MINOR_VERSION // 5
   .field_id =  { .raw  = 0x0800000100000003 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (-1ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_MB, .mig_import = MIG_CBO 
 },
 {
   // MAJOR_VERSION // 6
   .field_id =  { .raw  = 0x0800000100000004 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (-1ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_MB, .mig_import = MIG_CBO 
 },
 {
   // UPDATE_VERSION // 7
   .field_id =  { .raw  = 0x0800000100000005 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (-1ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_MB, .mig_import = MIG_CBO 
 },
 {
   // INTERNAL_VERSION // 8
   .field_id =  { .raw  = 0x0800000100000006 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (-1ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_MB, .mig_import = MIG_CBO 
 },
 {
   // MODULE_HV // 9
   .field_id =  { .raw  = 0x8900000100000000 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // MIN_UPDATE_HV // 10
   .field_id =  { .raw  = 0x8900000100000001 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // NO_DOWNGRADE // 11
   .field_id =  { .raw  = 0x8900000000000002 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFULL), .vmm_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // NUM_HANDOFF_PAGES // 12
   .field_id =  { .raw  = 0x8900000100000003 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // HANDOFF_DATA_VALID // 13
   .field_id =  { .raw  = 0x8900000000000004 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFULL), .vmm_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // HANDOFF_DATA_HV // 14
   .field_id =  { .raw  = 0x8900000100000005 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // HANDOFF_DATA_SIZE // 15
   .field_id =  { .raw  = 0x8900000200000006 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // SYS_ATTRIBUTES // 16
   .field_id =  { .raw  = 0x0A00000200000000 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_MB, .mig_import = MIG_CBO 
 },
 {
   // NUM_TDX_FEATURES // 17
   .field_id =  { .raw  = 0x0A00000000000001 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFULL), .vmm_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (-1ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (-1ULL & 0xFFULL), .import_mask = (-1ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_MB, .mig_import = MIG_CBO 
 },
 {
   // TDX_FEATURES0 // 18
   .field_id =  { .raw  = 0x0A00000300000008 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = true, .special_wr_handling = true,
   .mig_export = MIG_MB, .mig_import = MIG_CBO 
 },
 {
   // NUM_CMRS // 19
   .field_id =  { .raw  = 0x9000000100000000 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // CMR_BASE // 20
   .field_id =  { .raw  = 0x9000000300000080 },
   .num_of_fields = 32, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // CMR_SIZE // 21
   .field_id =  { .raw  = 0x9000000300000100 },
   .num_of_fields = 32, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // MAX_TDMRS // 22
   .field_id =  { .raw  = 0x9100000100000008 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // MAX_RESERVED_PER_TDMR // 23
   .field_id =  { .raw  = 0x9100000100000009 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // PAMT_4K_ENTRY_SIZE // 24
   .field_id =  { .raw  = 0x9100000100000010 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // PAMT_2M_ENTRY_SIZE // 25
   .field_id =  { .raw  = 0x9100000100000011 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // PAMT_1G_ENTRY_SIZE // 26
   .field_id =  { .raw  = 0x9100000100000012 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // TDR_BASE_SIZE // 27
   .field_id =  { .raw  = 0x9800000100000000 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // TDCS_BASE_SIZE // 28
   .field_id =  { .raw  = 0x9800000100000100 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // TDCS_SIZE_PER_L2_VM // 29
   .field_id =  { .raw  = 0x9800000100000101 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // TDVPS_BASE_SIZE // 30
   .field_id =  { .raw  = 0x9800000100000200 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // TDVPS_SIZE_PER_L2_VM // 31
   .field_id =  { .raw  = 0x9800000100000201 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // ATTRIBUTES_FIXED0 // 32
   .field_id =  { .raw  = 0x1900000300000000 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // ATTRIBUTES_FIXED1 // 33
   .field_id =  { .raw  = 0x1900000300000001 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // XFAM_FIXED0 // 34
   .field_id =  { .raw  = 0x1900000300000002 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // XFAM_FIXED1 // 35
   .field_id =  { .raw  = 0x1900000300000003 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // NUM_CPUID_CONFIG // 36
   .field_id =  { .raw  = 0x9900000100000004 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // CPUID_CONFIG_LEAVES // 37
   .field_id =  { .raw  = 0x9900000300000400 },
   .num_of_fields = 32, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // CPUID_CONFIG_VALUES // 38
   .field_id =  { .raw  = 0x9900000300000500 },
   .num_of_fields = 32, .num_of_elem = 2,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // IA32_ARCH_CAPABILITIES_CONFIG_MASK // 39
   .field_id =  { .raw  = 0x9900000300000600 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // MIG_ATTRIBUTES // 40
   .field_id =  { .raw  = 0xA000000300000000 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // MIN_EXPORT_VERSION // 41
   .field_id =  { .raw  = 0x2000000100000001 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // MAX_EXPORT_VERSION // 42
   .field_id =  { .raw  = 0x2000000100000002 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // MIN_IMPORT_VERSION // 43
   .field_id =  { .raw  = 0x2000000100000003 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // MAX_IMPORT_VERSION // 44
   .field_id =  { .raw  = 0x2000000100000004 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // MAX_MIGS // 45
   .field_id =  { .raw  = 0xA000000100000010 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // NUM_IMMUTABLE_STATE_PAGES // 46
   .field_id =  { .raw  = 0xA000000000000020 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFULL), .vmm_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // NUM_TD_STATE_PAGES // 47
   .field_id =  { .raw  = 0xA000000000000021 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFULL), .vmm_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // NUM_VP_STATE_PAGES // 48
   .field_id =  { .raw  = 0xA000000000000022 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFULL), .vmm_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // MAX_SERV_TDS // 49
   .field_id =  { .raw  = 0xA100000100000000 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // SERVTD_ATTR_FIXED0 // 50
   .field_id =  { .raw  = 0xA100000300000001 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // SERVTD_ATTR_FIXED1 // 51
   .field_id =  { .raw  = 0xA100000300000002 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // GUEST_L2_GPA_ATTR_MASK // 52
   .field_id =  { .raw  = 0xA200000100000000 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // VM_CTLS_FIXED0 // 53
   .field_id =  { .raw  = 0xA200000300000001 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // VM_CTLS_FIXED1 // 54
   .field_id =  { .raw  = 0xA200000300000002 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // VPCU_L2_CTLS_FIXED0 // 55
   .field_id =  { .raw  = 0xA200000300000003 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // VCPU_L2_CTLS_FIXED1 // 56
   .field_id =  { .raw  = 0xA200000300000004 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // VPCU_L2_DEBUG_CTLS_FIXED0 // 57
   .field_id =  { .raw  = 0xA200000300000005 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // VCPU_L2_DEBUG_CTLS_FIXED1 // 58
   .field_id =  { .raw  = 0xA200000300000006 },
   .num_of_fields = 1, .num_of_elem = 1,
   .vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 }
};

