// Intel Proprietary
// 
// Copyright 2021 Intel Corporation All Rights Reserved.
// 
// Your use of this software is governed by the TDX Source Code LIMITED USE LICENSE.
// 
// The Materials are provided "as is," without any express or implied warranty of any kind including warranties
// of merchantability, non-infringement, title, or fitness for a particular purpose.

/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  based on architecture commit id "1b3f4514" 
 *  Spreadsheet Format Version - '6'
 **/

#ifndef _AUTO_GEN_MSR_CONFIG_LOOKUP_H_
#define _AUTO_GEN_MSR_CONFIG_LOOKUP_H_



#include "tdx_api_defs.h"
#include "helpers/helpers.h"


#define MAX_NUM_MSR_LOOKUP 133

typedef struct
{
    uint32_t start_address;
    uint32_t end_address;
    msr_bitmap_bit_type rd_bit_meaning;
    msr_bitmap_action rd_action;
    msr_bitmap_bit_type wr_bit_meaning;
    msr_bitmap_action wr_action;
} msr_lookup_t;

const msr_lookup_t msr_lookup[MAX_NUM_MSR_LOOKUP];

#endif /* _AUTO_GEN_MSR_CONFIG_LOOKUP_H_ */
