// Intel Proprietary
// 
// Copyright 2021 Intel Corporation All Rights Reserved.
// 
// Your use of this software is governed by the TDX Source Code LIMITED USE LICENSE.
// 
// The Materials are provided "as is," without any express or implied warranty of any kind including warranties
// of merchantability, non-infringement, title, or fitness for a particular purpose.

/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  Spreadsheet Format Version - '2'
 **/

#include "auto_gen/op_state_lookup.h"


const bool_t seamcall_state_lookup[MAX_SEAMCALL_LEAF][NUM_OP_STATES] = {
    [0] = {0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0 },
    [1] = {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    [2] = {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    [3] = {0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0 },
    [4] = {0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0 },
    [5] = {0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0 },
    [6] = {0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0 },
    [7] = {0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0 },
    [10] = {0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0 },
    [11] = {0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 },
    [12] = {0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 },
    [13] = {0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1 },
    [14] = {0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1 },
    [15] = {0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0 },
    [16] = {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    [17] = {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    [18] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 },
    [21] = {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    [22] = {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    [23] = {0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0 },
    [25] = {0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 },
    [26] = {0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 },
    [29] = {0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1 },
    [30] = {0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 },
    [38] = {0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0 },
    [39] = {0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0 },
    [43] = {0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1 },
    [48] = {1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0 },
    [49] = {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    [64] = {0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0 },
    [65] = {0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 },
    [66] = {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 },
    [68] = {0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0 },
    [70] = {0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 },
    [71] = {0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0 },
    [72] = {0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0 },
    [73] = {0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 },
    [74] = {0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 },
    [75] = {0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0 },
    [80] = {0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1 },
    [81] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0 },
    [82] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 },
    [83] = {0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0 },
    [84] = {0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0 },
    [85] = {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    [86] = {0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 },
    [87] = {0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 },
    [96] = {1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0 }
};



const bool_t servtd_bind_othertd_state_lookup[NUM_OP_STATES] = { 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0 };




const bool_t tdcall_state_lookup[MAX_TDCALL_LEAF][NUM_OP_STATES] = {
    [18] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 },
    [20] = {1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1 }
};



const state_flags_t state_flags_lookup[NUM_OP_STATES] = {
  [0] = {
    .tlb_tracking_required = 0,
    .any_initialized = 0,
    .any_finalized = 0,
    .export_in_order = 0,
    .import_in_order = 0,
    .import_out_of_order = 0,
    .import_in_progress = 0,
    .cpuid_writable_by_migtd = 0
  },
  [1] = {
    .tlb_tracking_required = 0,
    .any_initialized = 1,
    .any_finalized = 0,
    .export_in_order = 0,
    .import_in_order = 0,
    .import_out_of_order = 0,
    .import_in_progress = 0,
    .cpuid_writable_by_migtd = 1
  },
  [2] = {
    .tlb_tracking_required = 1,
    .any_initialized = 1,
    .any_finalized = 1,
    .export_in_order = 0,
    .import_in_order = 0,
    .import_out_of_order = 0,
    .import_in_progress = 0,
    .cpuid_writable_by_migtd = 0
  },
  [3] = {
    .tlb_tracking_required = 1,
    .any_initialized = 1,
    .any_finalized = 1,
    .export_in_order = 1,
    .import_in_order = 0,
    .import_out_of_order = 0,
    .import_in_progress = 0,
    .cpuid_writable_by_migtd = 0
  },
  [4] = {
    .tlb_tracking_required = 0,
    .any_initialized = 1,
    .any_finalized = 1,
    .export_in_order = 1,
    .import_in_order = 0,
    .import_out_of_order = 0,
    .import_in_progress = 0,
    .cpuid_writable_by_migtd = 0
  },
  [5] = {
    .tlb_tracking_required = 0,
    .any_initialized = 1,
    .any_finalized = 1,
    .export_in_order = 0,
    .import_in_order = 0,
    .import_out_of_order = 0,
    .import_in_progress = 0,
    .cpuid_writable_by_migtd = 0
  },
  [6] = {
    .tlb_tracking_required = 0,
    .any_initialized = 1,
    .any_finalized = 1,
    .export_in_order = 0,
    .import_in_order = 1,
    .import_out_of_order = 0,
    .import_in_progress = 1,
    .cpuid_writable_by_migtd = 0
  },
  [7] = {
    .tlb_tracking_required = 0,
    .any_initialized = 1,
    .any_finalized = 1,
    .export_in_order = 0,
    .import_in_order = 1,
    .import_out_of_order = 0,
    .import_in_progress = 1,
    .cpuid_writable_by_migtd = 0
  },
  [8] = {
    .tlb_tracking_required = 0,
    .any_initialized = 1,
    .any_finalized = 1,
    .export_in_order = 0,
    .import_in_order = 0,
    .import_out_of_order = 1,
    .import_in_progress = 1,
    .cpuid_writable_by_migtd = 0
  },
  [9] = {
    .tlb_tracking_required = 1,
    .any_initialized = 1,
    .any_finalized = 1,
    .export_in_order = 0,
    .import_in_order = 0,
    .import_out_of_order = 1,
    .import_in_progress = 1,
    .cpuid_writable_by_migtd = 0
  },
  [10] = {
    .tlb_tracking_required = 0,
    .any_initialized = 1,
    .any_finalized = 0,
    .export_in_order = 0,
    .import_in_order = 0,
    .import_out_of_order = 0,
    .import_in_progress = 0,
    .cpuid_writable_by_migtd = 0
  }
};



