// Intel Proprietary
// 
// Copyright 2021 Intel Corporation All Rights Reserved.
// 
// Your use of this software is governed by the TDX Source Code LIMITED USE LICENSE.
// 
// The Materials are provided "as is," without any express or implied warranty of any kind including warranties
// of merchantability, non-infringement, title, or fitness for a particular purpose.

/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  based on architecture commit id "1b3f4514" 
 *  Spreadsheet Format Version - '24'
 **/

#ifndef _AUTO_GEN_TD_L2_VMCS_FIELDS_LOOKUP_H_
#define _AUTO_GEN_TD_L2_VMCS_FIELDS_LOOKUP_H_



#include "tdx_api_defs.h"
#include "metadata_handlers/metadata_generic.h"


#define MAX_NUM_TD_L2_VMCS_LOOKUP 144

extern const md_lookup_t td_l2_vmcs_lookup[MAX_NUM_TD_L2_VMCS_LOOKUP];

#endif /* _AUTO_GEN_TD_L2_VMCS_FIELDS_LOOKUP_H_ */
